config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "songs#index"
  get "up" => "rails/health#show", as: :rails_health_check

  resources :leagues, only: [:index]
  
  resources :playlists, only: [:index] do
    collection do
      post :scrape
    end

    member do
      patch :update_spotify_created_at
      post :import_songs
    end
  end

  resources :songs, only: [:index] do
    collection do
      post :import # bulk import
      get :export_csv
    end
  end

  resources :stats, only: [:index]

  namespace :admin do
    resources :leagues
    resources :users, only: [:index] do
      patch :toggle_admin, on: :member
    end
  end
end

app/models/league.rb
# == Schema Information
#
# Table name: leagues
#
#  id              :bigint           not null, primary key
#  name            :string
#  url             :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  music_league_id :string
#
# Indexes
#
#  index_leagues_on_music_league_id  (music_league_id) UNIQUE
#
class League < ApplicationRecord
  has_many :playlists, dependent: :destroy
  has_many :league_memberships
  has_many :users, through: :league_memberships
end

app/controllers/admin/leagues_controller.rb
class Admin::LeaguesController < Admin::BaseController
  before_action :set_league, only: [:edit, :update, :destroy]

  def index
    @leagues = League.all.order(created_at: :desc)
  end

  def new
    @league = League.new
  end

  def create
    @league = League.new(league_params)
    if @league.save
      redirect_to admin_leagues_path, notice: "League created successfully."
    else
      render :new
    end
  end

  def edit; end

  def update
    if @league.update(league_params)
      redirect_to admin_leagues_path, notice: "League updated successfully."
    else
      render :edit
    end
  end

  def destroy
    @league.destroy
    redirect_to admin_leagues_path, notice: "League deleted."
  end

  private

  def set_league
    @league = League.find(params[:id])
  end

  def league_params
    params.require(:league).permit(:name, :music_league_id, :url)
  end
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController

  def index
    @leagues = League.all.order(id: :desc)
  end
end

app/views/admin/leagues/_form.html.erb
<%= form_with(model: [:admin, @league], local: true) do |f| %>
  <div class="mb-3">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= f.label :music_league_id, "Music League ID" %>
    <%= f.text_field :music_league_id, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= f.label :url %>
    <%= f.url_field :url, class: "form-control" %>
  </div>

  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/admin/leagues/edit.html.erb
<%= render "admin/shared/nav" %>

<h1><%= action_name.capitalize %> League</h1>
<%= render "form" %>
<%= link_to "Back", admin_leagues_path, class: "btn btn-secondary mt-3" %>

app/views/admin/leagues/index.html.erb
<%= render "admin/shared/nav" %>

<h1>Leagues</h1>
<%= link_to "Add New League", new_admin_league_path, class: "btn btn-primary mb-3" %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Music League ID</th>
      <th>URL</th>
      <th>Created At</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @leagues.each do |league| %>
      <tr>
        <td><%= league.name %></td>
        <td><%= league.music_league_id %></td>
        <td><%= league.url %></td>
        <td><%= league.created_at.strftime("%Y-%m-%d") %></td>
        <td>
          <%= link_to "Edit", edit_admin_league_path(league), class: "btn btn-sm btn-primary" %>
          <%= link_to "Delete", admin_league_path(league), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-sm btn-danger" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/leagues/new.html.erb
<%= render "admin/shared/nav" %>

<h1><%= action_name.capitalize %> League</h1>
<%= render "form" %>
<%= link_to "Back", admin_leagues_path, class: "btn btn-secondary mt-3" %>