config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "songs#index"
  get "up" => "rails/health#show", as: :rails_health_check

  resources :leagues, only: [:index]
  
  resources :playlists, only: [:index] do
    collection do
      post :scrape
    end

    member do
      patch :update_spotify_created_at
      post :import_songs
    end
  end

  resources :songs, only: [:index] do
    collection do
      post :import # bulk import
      get :export_csv
    end
  end

  resources :stats, only: [:index]

  namespace :admin do
    resources :leagues
    resources :users, only: [:index] do
      patch :toggle_admin, on: :member
    end
  end
end

app/views/shared/_nav_bar.html.erb
<nav class="navbar navbar-expand-md bg-primary mb-4">
  <div class="container-fluid">
    <span class="navbar-brand">ML Playlist History</span>

    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#mainNavbar"
      aria-controls="mainNavbar"
      aria-expanded="false"
      aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="mainNavbar">
      <ul class="navbar-nav me-auto mb-2 mb-md-0">
        <li class="nav-item">
          <%= link_to 'Leagues', leagues_path, class: "nav-link #{'active' if current_page?(leagues_path)}" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Playlists', playlists_path, class: "nav-link #{'active' if current_page?(playlists_path)}" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Songs', songs_path, class: "nav-link #{'active' if current_page?(songs_path)}" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Stats', stats_path, class: "nav-link #{'active' if current_page?(stats_path)}" %>
        </li>
        <% if user_signed_in? && current_user.admin? %>
          <li class="nav-item">
            <%= link_to "Admin", admin_users_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>

      <ul class="navbar-nav">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <% if user_signed_in? %>
              <%= current_user.email %>
            <% else %>
              Account
            <% end %>
          </a>
          <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="userDropdown">
            <% if user_signed_in? %>
              <li><%= link_to "Edit Profile", edit_user_registration_path, class: "dropdown-item" %></li>
              <li><hr class="dropdown-divider"></li>
              <li>
                <%= button_to "Logout", destroy_user_session_path,
                      method: :delete,
                      form_class: "d-inline",
                      class: "dropdown-item" %>
              </li>
            <% else %>
              <li><%= link_to "Login", new_user_session_path, class: "dropdown-item" %></li>
              <li><%= link_to "Sign Up", new_user_registration_path, class: "dropdown-item" %></li>
            <% end %>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>