config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "songs#index"
  get "up" => "rails/health#show", as: :rails_health_check

  resources :leagues, only: [:index]
  
  resources :playlists, only: [:index] do
    collection do
      post :scrape
    end

    member do
      patch :update_spotify_created_at
      post :import_songs
    end
  end

  resources :songs, only: [:index] do
    collection do
      post :import # bulk import
      get :export_csv
    end
  end

  resources :stats, only: [:index]

  namespace :admin do
    resources :leagues
    resources :users, only: [:index] do
      patch :toggle_admin, on: :member
    end
  end
end

app/models/playlist.rb
# == Schema Information
#
# Table name: playlists
#
#  id                 :bigint           not null, primary key
#  name               :string
#  round_number       :integer
#  spotify_created_at :datetime
#  spotify_url        :string
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  league_id          :bigint           not null
#
# Indexes
#
#  index_playlists_on_league_id  (league_id)
#
# Foreign Keys
#
#  fk_rails_...  (league_id => leagues.id)
#
class Playlist < ApplicationRecord
  belongs_to :league
  has_many :playlist_songs, dependent: :destroy
  has_many :songs, through: :playlist_songs
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  before_action :set_league, only: [:scrape]

  def index
    @playlists = Playlist.all
                         .includes(:league)
                         .joins(:league)
                         .order('leagues.created_at DESC, playlists.round_number DESC')
  end

  def update_spotify_created_at
    playlist = Playlist.find(params[:id])

    playlist_id = playlist.spotify_url.match(/playlist\/([^?]+)/)[1]
    tracks_data = SpotifyClient.new.fetch_playlist_tracks(playlist_id)
    all_tracks = tracks_data.flat_map { |t| t[:tracks] || [] } rescue []
    first_added_at = all_tracks.min_by { |t| t[:added_at] }&.[](:added_at)

    if first_added_at.present?
      playlist.update(spotify_created_at: first_added_at)
      redirect_to playlists_path, notice: "Spotify created_at updated for #{playlist.name}"
    else
      redirect_to playlists_path, alert: "Could not determine created_at for #{playlist.name}"
    end
  end

  def scrape
    authorize Playlist, :scrape?

    urls_with_rounds = MusicLeagueScraperService.new.call

    urls_with_rounds.each do |playlist_data|
      Playlist.find_or_create_by(
        spotify_url: playlist_data[:url],
        round_number: playlist_data[:round_number],
        name: playlist_data[:name],
        league: @league
      )
    end

    redirect_to playlists_path, notice: "Playlists fetched and updated for league #{@league.name}."
  end

  def import_songs
    playlist = Playlist.find(params[:id])
    imported_tracks = PlaylistSongImporter.new.call(playlist)
    
    imported_tracks.each do |track_attrs|
      song = Song.find_or_create_by!(title: track_attrs[:title], artist: track_attrs[:artist]) do |s|
        s.album = track_attrs[:album_name] if track_attrs[:album_name]
      end
      
      PlaylistSong.find_or_create_by!(playlist: playlist, song: song)
    end

    redirect_to playlists_path, notice: "Songs imported successfully."
  end

  private

  def set_league
    @league = League.last # Set to current league
  end
end

app/views/playlists/index.html.erb
<h1>Playlists</h1>

<% if policy(Playlist).scrape? %>
  <%= button_to "Fetch from Music League", scrape_playlists_path, method: :post %>
<% end %>

<br>

<div class="table-responsive">
  <table class="table table-bordered table-hover table-sm">
    <thead class="thead-light sticky-top bg-white" style="z-index: 1">
      <tr>
        <th>League</th>
        <th>Round</th>
        <th>Name</th>
        <th class="d-none d-md-table-cell">Created At</th>
      </tr>
    </thead>
    <tbody>
      <% @playlists.each do |playlist| %>
        <tr>
          <td><%= playlist.league.name %></td>
          <td><%= playlist.round_number %></td>
          <td><%= playlist.name %></td>
          <td class="d-none d-md-table-cell">
            <% if playlist.spotify_created_at.present? %>
              <%= playlist.spotify_created_at.strftime("%Y-%m-%d") %>
            <% else %>
              <% if policy(playlist).update? %>
                <%= button_to "Update", update_spotify_created_at_playlist_path(playlist),
                              method: :patch,
                              form_class: "d-inline",
                              class: "btn btn-sm btn-outline-primary" %>
              <% end %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>